"""Added activity_destinations association table

Revision ID: b666838bb243
Revises: 
Create Date: 2025-01-05 00:11:07.495360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b666838bb243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('Destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Destinations_id'), ['id'], unique=False)

    op.drop_table('destinations')
    with op.batch_alter_table('travelgroups', schema=None) as batch_op:
        batch_op.drop_index('group_name')

    op.drop_table('travelgroups')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('users')
    op.drop_table('groupmembers')
    op.drop_table('activities')
    op.drop_table('reviews')
    with op.batch_alter_table('activity_destinations', schema=None) as batch_op:
        batch_op.alter_column('destination_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('activity_destinations_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('activity_destinations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Destinations', ['destination_name'], ['name'])
        batch_op.create_foreign_key(None, 'Activities', ['activity_id'], ['id'])

    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('Destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Destinations_id'), ['id'], unique=False)

    op.create_table('TravelGroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('GroupMembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['TravelGroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['Destinations.id'], ),
    sa.ForeignKeyConstraint(['username'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index('ix_Destinations_id')
        batch_op.drop_index('ix_Destinations_name')

    op.drop_table('destinations')
    with op.batch_alter_table('travelgroups', schema=None) as batch_op:
        batch_op.drop_index('group_name')

    op.drop_table('travelgroups')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('users')
    op.drop_table('groupmembers')
    op.drop_table('activities')
    op.drop_table('reviews')
    with op.batch_alter_table('activity_destinations', schema=None) as batch_op:
        batch_op.alter_column('destination_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('activity_destinations_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('activity_destinations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Destinations', ['destination_name'], ['name'])
        batch_op.create_foreign_key(None, 'Activities', ['activity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_destinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activity_destinations_ibfk_1', 'activities', ['activity_id'], ['id'])
        batch_op.create_foreign_key('activity_destinations_ibfk_2', 'destinations', ['destination_name'], ['name'])
        batch_op.alter_column('destination_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('reviews',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('destination_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name='reviews_ibfk_2'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='reviews_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_participants', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('groupmembers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['travelgroups.id'], name='groupmembers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('travelgroups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('contact_info', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('travelgroups', schema=None) as batch_op:
        batch_op.create_index('group_name', ['group_name'], unique=True)

    op.create_table('destinations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activities', mysql.TEXT(), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.create_index('ix_Destinations_name', ['name'], unique=False)
        batch_op.create_index('ix_Destinations_id', ['id'], unique=False)

    op.drop_table('Reviews')
    op.drop_table('GroupMembers')
    op.drop_table('Users')
    op.drop_table('TravelGroups')
    with op.batch_alter_table('Destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Destinations_id'))

    op.drop_table('Destinations')
    op.drop_table('Activities')
    # ### end Alembic commands ###
